feat: 질문 등록
CNU-Software-Acadmey/cagong-backend pull request #5
Opened 2022-09-27 12:03 UTC by beautiflow

작성자는 로그인 기능이 완료되면 추가하겠습니다~!

2022-09-27 15:54 UTC, Kim-AYoung commented
LGTM 👍

2022-10-15 10:42 UTC, sanggyunbak2856 requested changes

2022-10-15 10:42 UTC, sanggyunbak2856 commented on src/main/java/kr/ac/cnu/swacademy/cagong/controller/api/QuestionApiController.java
> +        questionService.댓글쓰기(answerSaveRequestDto);
questionService.댓글쓰기는 어떤 기능인가요?
메서드 이름이 한글로 되어있는데 영어로 써야하지 않을까요?

2022-10-15 10:42 UTC, sanggyunbak2856 commented on src/main/java/kr/ac/cnu/swacademy/cagong/service/question/QuestionService.java
> +    public void 댓글쓰기(AnswerSaveRequestDto answerSaveRequestDto) {
메서드 이름을 변경하는 것이 좋을 것 같습니다

2022-10-15 10:45 UTC, sanggyunbak2856 approved these changes
메서드 이름을 변경하는 것이 좋을 것 같습니다

2022-10-15 10:45 UTC, sanggyunbak2856 commented on src/main/java/kr/ac/cnu/swacademy/cagong/service/question/QuestionService.java
> +    public void 댓글쓰기(AnswerSaveRequestDto answerSaveRequestDto) {
메서드 이름을 바꾸는 것이 좋을것같습니다

2022-10-15 10:46 UTC, sanggyunbak2856 reviewed
메서드 이름을 바꾸는 것이 좋을것같습니다

2022-10-19 00:41 UTC, beautiflow commented on src/main/java/kr/ac/cnu/swacademy/cagong/service/question/QuestionService.java
> +    public void 댓글쓰기(AnswerSaveRequestDto answerSaveRequestDto) {
네 감사합니다 :)

2022-10-21 03:50 UTC, merged